### ISSUE TITLE
Introduce artifact synchronization support in WSO2 API Manager deployment patterns

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/pivotal-cf-apim#28]
**Description:**
Artifact synchronization support for WSO2 API Manager deployment patterns need to be introduced. This has to be addressed using CloudFoundry BOSH constructs.

**Suggested Labels:**
Type/New Feature

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
2.1.0.2

**Related Issues:**
https://github.com/wso2/pivotal-cf-apim/issues/10

**Comment by imesh** [comment]
We already have five tasks for implementing BOSH releases for five deployment patterns of WSO2 API-M. All features required for each deployment pattern need to be addressed in those tasks. IMO it would be better to implement support for each pattern iteratively rather than trying to implement them in all patterns at once. Thanks!

**Comment by chirangaalwis** [comment]
A related issue https://github.com/cloudfoundry/bosh/issues/1881.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/pivotal-cf-apim/pull/35.
