### ISSUE TITLE
Fix issues and revamp the export.sh script of BOSH Release for WSO2 API Manager deployment pattern 1

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/pivotal-cf-apim#29]
**Description:**
The purpose of the export.sh script is to create a release tarball for a BOSH release of a particular deployment scenario. The existing implementation does not reflect the entire BOSH release export process.

The existing implementation of export.sh simply contains the BOSH CLI command to create a BOSH release and export the tarball. Ideally if this script is to be executed independently, prior to exporting the tarball, the script should perform the necessary tasks such as, identifying which BOSH environment to use, uploading the blobs and creating the release.

This needs to be fixed.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
2.1.0.2

**Related Issues:**
https://github.com/wso2/pivotal-cf-apim/issues/10

**Comment by imesh** [comment]
@chirangaalwis I think it would be better if we can remove all the helper bash scripts and provide instructions in the README.md file for all the operations needed for building the BOSH release and CF Tile. WDYT? This is mainly to reduce the maintenance overhead of helper scripts and because BOSH releases and CF tiles will be released for API Manager to be used by the users.
